Update Xsite.md
form = dict([queryParam.split('=') for queryParam in queryStr.split('&amp;')]) 
results in the error: 
ValueError: dictionary update sequence element #0 has length 3; 2 is required
Removing the amp; from the second split argument worked for me.
form = dict([queryParam.split('=') for queryParam in queryStr.split('&')])